[package]
name = "tpvbc2http"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
colog = "1.3.0"
tinyhttp =  { version = "0.5.0", default-features = false }
# openssl = { version = "0.10", features = ["vendored"] }
notify = "6.1.1"
clap = { version = "4.5.23", features = ["derive"] }
