[package]
name = "tpvbc2http"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
colog = "1.3.0"
notify = "6.1.1"
clap = { version = "4.5.23", features = ["derive"] }
# simple-server = "0.4.0"
simple-server = { path = "./lib/simple-server" }
unicode-bom = "=2.0.3"
bus = "2.4.1"