on: [push, pull_request, workflow_dispatch]

name: CI

env:
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: windows-latest
          TARGET: x86_64-pc-windows-msvc
          EXTENSION: .exe
    steps:
    - name: Building ${{ matrix.TARGET }}
      run: echo "${{ matrix.TARGET }}"

    - uses: actions/checkout@master
    - name: Install build dependencies - Rustup
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain stable --profile default --target ${{ matrix.TARGET }} -y
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install cross for mac and windows
      if: ${{ !contains(matrix.TARGET, 'linux') }}
      run: |
        cargo install cross

    - name: Build
      run: |
        cross build --verbose --release --target=${{ matrix.TARGET }}

    - name: Rename
      run: cp target/${{ matrix.TARGET }}/release/tpvbc2http${{ matrix.EXTENSION }} tpvbc2http-${{ matrix.TARGET }}${{ matrix.EXTENSION }}

    - uses: actions/upload-artifact@master
      with:
        name: tpvbc2http-${{ matrix.TARGET }}${{ matrix.EXTENSION }}
        path: tpvbc2http-${{ matrix.TARGET }}${{ matrix.EXTENSION }}

#    - uses: svenstaro/upload-release-action@v2
#      name: Upload binaries to release
#      if: ${{ github.event_name == 'push' }}
#      with:
#        repo_token: ${{ secrets.GITHUB_TOKEN }}
#        file: tpvbc2http-${{ matrix.TARGET }}${{ matrix.EXTENSION }}
#        asset_name: tpvbc2http-${{ matrix.TARGET }}${{ matrix.EXTENSION }}
#        tag: ${{ github.ref }}
#        prerelease: ${{ !startsWith(github.ref, 'refs/tags/') }}
#        overwrite: true
